### ISSUE TITLE
Expose the custom StyledIconProps

### ISSUE THREAD

**Issue by zenVentzi** [jacobwgillespie/styled-icons#660]
Hi, I have cases where I want to create some default components, e.g.

```
import React from "react";
import { Menu } from "styled-icons/material/Menu";

const MenuBtn = (props: any) => {
  // some default functionality
  return <Menu size="2em" css="cursor: pointer" /* some other default props */ {...props} />;
};

export default MenuBtn;

```

Problem is with the props: any. I tried importing StyledIconProps from the base directory but the types are incompatible. 

The goal is to be able to do sth like:
`
import { Menu, MenuProps } from "styled-icons/material/Menu";
`

and then `(props: MenuProps)`

or any other solution that will help not use any types.

**Comment by jacobwgillespie** [comment]
This should already exist as `import {StyledIconProps} from 'styled-icons/types'`, so something like:

```typescript
import React from "react";
import { Menu } from "styled-icons/material/Menu";
import { StyledIconProps } from "styled-icons";

const MenuBtn = (props: StyledIconProps) => {
  // some default functionality
  return <Menu size="2em" css="cursor: pointer" /* some other default props */ {...props} />;
};

export default MenuBtn;
```

While verifying that worked, I discovered that the `ref` prop was incorrectly typed inside `StyledIconProps`, so that fix has been released as `v4.7.1` - you'll want to upgrade to ensure the above approach works.

Also note you may want to use `React.FC` instead of typing the `props` directly (not related to `styled-icons`, you'll just get more accurate props with things like `children` included):

```typescript
import React from "react";
import { Menu } from "styled-icons/material/Menu";
import { StyledIconProps } from "styled-icons";

const MenuBtn: React.FC<StyledIconProps> = props => {
  // some default functionality
  return <Menu size="2em" css="cursor: pointer" /* some other default props */ {...props} />;
};

export default MenuBtn;
```

**Comment by zenVentzi** [comment]
Just updated to `v4.7.2` but still getting errors. Code:

```
import React from "react";
import { Menu } from "styled-icons/material/Menu";
import { StyledIconProps } from "styled-icons/types";

const MenuBtn = (props: StyledIconProps) => {
  return <Menu size="2em" css="cursor: pointer" {...props} />;
};

export default MenuBtn;

```

Error:

```
Type '{ 'aria-hidden'?: string | undefined; size: string | number; title?: string | null | undefined; className?: string | undefined; color?: string | undefined; height?: string | number | undefined; ... 415 more ...; css: CSSProp<...>; }' is not assignable to type 'RefAttributes<SVGSVGElement>'.
  Types of property 'ref' are incompatible.
    Type 'string | ((instance: SVGSVGElement | null) => void) | RefObject<SVGSVGElement> | null | undefined' is not assignable to type '((instance: SVGSVGElement | null) => void) | RefObject<SVGSVGElement> | null | undefined'.
      Type 'string' is not assignable to type '((instance: SVGSVGElement | null) => void) | RefObject<SVGSVGElement> | null | undefined'.ts(2322)
(alias) const Menu: React.ForwardRefExoticComponent<Pick<StyledIconProps, "string" | "max" | "accumulate" | "end" | "hanging" | "alphabetic" | "ideographic" | "media" | "style" | "title" | "clipPath" | "cursor" | "filter" | ... 406 more ... | "aria-hidden"> & React.RefAttributes<...>>
import Menu

```

**Comment by zenVentzi** [comment]
Awesome, appreciate it! v7.4.2 works as expected.

P.s. if somebody reads this and it doesn't work, I had to restart VSCode after the package update.

**Comment by jacobwgillespie** [comment]
Awesome, glad that worked!
